### ISSUE TITLE
Issue in making migrations with docker-compose

### ISSUE THREAD

**Issue by gtljaymodi** [robromano/django-adminrestrict#13]
Can you add migrations in the repo and re-release?

**Comment by gtljaymodi** [comment]
I have `python manage.py makemigrations adminrestrict` at entrypoint.sh file.

Error logs:
```
web_1    | Waiting for postgres...
web_1    | PostgreSQL started
web_1    | Migrations for 'adminrestrict':
web_1    |   /usr/local/lib/python3.7/site-packages/adminrestrict/migrations/0001_initial.py
web_1    |     - Create model AllowedIP
web_1    | Traceback (most recent call last):
web_1    |   File "manage.py", line 21, in <module>
web_1    |     main()
web_1    |   File "manage.py", line 17, in main
web_1    |     execute_from_command_line(sys.argv)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
web_1    |     utility.execute()
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
web_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
web_1    |     self.execute(*args, **cmd_options)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
web_1    |     output = self.handle(*args, **options)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
web_1    |     res = handle_func(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 182, in handle
web_1    |     self.write_migration_files(changes)
web_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 214, in write_migration_files
web_1    |     os.mkdir(migrations_directory)
web_1    | PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/adminrestrict/migrations'
```

**Comment by robromano** [comment]
Can you modify permissions to /usr/local/lib/python3.7/site-packages/adminrestrict/migrations directly in the docker container?

**Comment by gtljaymodi** [comment]
Thank you @robromano for adding migrations :+1:

**Comment by robromano** [comment]
The Django docs are not super clear about committing initial migrations to projects but after doing a little research it appears this is the recommended pattern.  

However the Django docs just say “you may need to ship migrations”, and do recommend using the lowest Django version you wish to support to create them.  The header for this section is “Supporting múltiple Django versions” on this page: https://docs.djangoproject.com/en/3.0/topics/migrations/

Documenting this info for anyone else who comes across this ticket as a package maintainer.
