### ISSUE TITLE
Under Django 2.0 it dosen't work

### ISSUE THREAD

**Issue by rookie10** [robromano/django-adminrestrict#8]
after installing adminrestrict under python3 and Django 2.0 i get the following problem

```
System check identified no issues (0 silenced).
February 15, 2018 - 19:26:58
Django version 2.0, using settings 'webcont.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x75795f18>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "/usr/local/lib/python3.4/dist-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/src/webcont/webcont/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.4/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 140, in __init__
    self.load_middleware()
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 39, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```

**Comment by robromano** [comment]
Thanks.  Do you have any time to fix and upgrade and submit a PR?

**Comment by rookie10** [comment]
Sorry,  time be not the problem but my skills for django are not good enough to fix it.

**Comment by robromano** [comment]
I merged your pull request, please update this ticket if you get a chance and thank you.

**Comment by kamilsj** [comment]
Is this app actively developed?

**Comment by robromano** [comment]
I haven’t been working on it recently but what it does is fairly simple.
I’ve tried to keep it up to date for newer Django versions but sometimes
fall behind.

If you have time for pull requests to fix stuff it’s much appreciated.

**Comment by kamilsj** [comment]
@robromano sure, I will take a look 👍

**Comment by javguitor** [comment]
@robromano and @kamilsj  I think that you should be use MiddlewareMixin (https://github.com/django/django/blob/1.11.15/django/utils/deprecation.py)


12:01

**Comment by robromano** [comment]
We merged in a pull request that addresses using middleware mixin.

**Comment by robromano** [comment]
I added Django 2.0.13 to Travis to assist in fixing this.  If  you have time to loook at the errores willing to take a pull request as a fix.

**Comment by robromano** [comment]
I've updated the package to support Django 2.0/2.1.  Will be pushing new version of the entire package to PyPi.

Thanks
